-- 1. Current DT status (immediate)
SHOW DYNAMIC TABLES IN SCHEMA CUSTOMER_360.DEV_DIL_CUS;

-- 2. Refresh history via ACCOUNT_USAGE (up to 365 days, ~45 min latency)
SELECT NAME, REFRESH_ACTION, REFRESH_TRIGGER, STATE, STATE_MESSAGE,
       DATA_TIMESTAMP, REFRESH_START_TIME, REFRESH_END_TIME, STATISTICS
FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
WHERE SCHEMA_NAME = 'DEV_DIL_CUS'
  AND DATABASE_NAME = 'CUSTOMER_360'
ORDER BY REFRESH_START_TIME DESC
LIMIT 20;

-- 3. Manual refresh with inline stats (immediate)
ALTER DYNAMIC TABLE CUSTOMER_360.DEV_DIL_CUS.CLEAN_CUSTOMER_PROFILES REFRESH;
ALTER DYNAMIC TABLE CUSTOMER_360.DEV_DIL_CUS.CUSTOMER_SUMMARY REFRESH;


SELECT
    SERVICE_TYPE,
    ROUND(SUM(CREDITS_USED), 2) AS TOTAL_CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY SERVICE_TYPE
ORDER BY TOTAL_CREDITS_USED DESC