-- =============================================================================
-- 04_curated_dynamic_tables.sql - CURATED Layer
-- Unified Customer 360 view and interaction timeline
-- =============================================================================

USE DATABASE CUSTOMER_360;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- CUSTOMER_360_UNIFIED - Master 360 record per customer
-- Joins all domains into a single denormalized row per customer
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CURATED.CUSTOMER_360_UNIFIED
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = COMPUTE_WH
AS
WITH policy_agg AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_POLICIES,
        SUM(CASE WHEN POLICY_STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_POLICIES,
        SUM(CASE WHEN POLICY_STATUS IN ('LAPSED', 'CANCELLED') THEN 1 ELSE 0 END) AS LAPSED_POLICIES,
        SUM(PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
        AVG(PREMIUM_AMOUNT) AS AVG_PREMIUM,
        MAX(COVERAGE_AMOUNT) AS MAX_COVERAGE,
        LISTAGG(DISTINCT POLICY_TYPE, ', ') WITHIN GROUP (ORDER BY POLICY_TYPE) AS POLICY_TYPES,
        MODE(RISK_CATEGORY) AS PRIMARY_RISK_CATEGORY,
        MIN(DAYS_TO_RENEWAL) AS NEXT_RENEWAL_DAYS
    FROM CLEAN.DT_POLICIES
    GROUP BY CUSTOMER_ID
),
claims_agg AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_CLAIMS,
        SUM(CASE WHEN CLAIM_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_CLAIMS,
        SUM(CASE WHEN CLAIM_STATUS = 'DENIED' THEN 1 ELSE 0 END) AS DENIED_CLAIMS,
        SUM(CLAIM_AMOUNT) AS TOTAL_CLAIM_AMOUNT,
        AVG(SETTLEMENT_RATIO) AS AVG_SETTLEMENT_RATIO,
        AVG(DAYS_TO_RESOLVE) AS AVG_CLAIM_RESOLUTION_DAYS,
        MAX(FILED_DATE) AS LAST_CLAIM_DATE
    FROM CLEAN.DT_CLAIMS
    GROUP BY CUSTOMER_ID
),
loan_agg AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_LOANS,
        SUM(CASE WHEN LOAN_STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_LOANS,
        SUM(CASE WHEN LOAN_STATUS IN ('DEFAULT', 'DELINQUENT') THEN 1 ELSE 0 END) AS PROBLEM_LOANS,
        SUM(OUTSTANDING_BALANCE) AS TOTAL_OUTSTANDING_BALANCE,
        SUM(MONTHLY_PAYMENT) AS TOTAL_MONTHLY_PAYMENT,
        MAX(DAYS_PAST_DUE) AS MAX_DAYS_PAST_DUE,
        LISTAGG(DISTINCT LOAN_TYPE, ', ') WITHIN GROUP (ORDER BY LOAN_TYPE) AS LOAN_TYPES
    FROM CLEAN.DT_LOANS
    GROUP BY CUSTOMER_ID
),
interaction_agg AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_INTERACTIONS,
        SUM(CASE WHEN INTERACTION_TYPE = 'Complaint' THEN 1 ELSE 0 END) AS COMPLAINT_COUNT,
        SUM(CASE WHEN RESOLUTION_STATUS = 'ESCALATED' THEN 1 ELSE 0 END) AS ESCALATION_COUNT,
        MAX(INTERACTION_DATE) AS LAST_INTERACTION_DATE,
        MODE(CHANNEL) AS PREFERRED_CHANNEL,
        DATEDIFF('day', MAX(INTERACTION_DATE), CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_INTERACTION
    FROM CLEAN.DT_INTERACTIONS
    GROUP BY CUSTOMER_ID
),
transcript_agg AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_CALLS,
        MAX(CALL_DATE) AS LAST_CALL_DATE,
        AVG(DURATION_SECONDS) AS AVG_CALL_DURATION,
        MODE(CALL_REASON) AS MOST_COMMON_CALL_REASON
    FROM CLEAN.DT_CALL_TRANSCRIPTS
    GROUP BY CUSTOMER_ID
),
document_agg AS (
    SELECT
        TRY_CAST(CUSTOMER_ID AS NUMBER) AS CUSTOMER_ID,
        COUNT(*) AS TOTAL_DOCUMENTS,
        LISTAGG(DISTINCT DOCUMENT_TYPE, ', ') WITHIN GROUP (ORDER BY DOCUMENT_TYPE) AS DOCUMENT_TYPES,
        MAX(FILE_MODIFIED_AT) AS LAST_DOCUMENT_DATE
    FROM AI.DT_DOCUMENT_EXTRACTED
    WHERE TRY_CAST(CUSTOMER_ID AS NUMBER) IS NOT NULL
    GROUP BY TRY_CAST(CUSTOMER_ID AS NUMBER)
)
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.EMAIL,
    c.PHONE,
    c.AGE,
    c.CITY,
    c.STATE,
    c.COUNTRY,
    c.CUSTOMER_SEGMENT,
    c.CREDIT_SCORE,
    c.ANNUAL_INCOME,
    c.EMPLOYMENT_STATUS,
    c.IS_ACTIVE,
    c.TENURE_MONTHS,
    -- Policy metrics
    COALESCE(p.TOTAL_POLICIES, 0) AS TOTAL_POLICIES,
    COALESCE(p.ACTIVE_POLICIES, 0) AS ACTIVE_POLICIES,
    COALESCE(p.LAPSED_POLICIES, 0) AS LAPSED_POLICIES,
    COALESCE(p.TOTAL_PREMIUM, 0) AS TOTAL_PREMIUM,
    p.AVG_PREMIUM,
    p.MAX_COVERAGE,
    p.POLICY_TYPES,
    p.PRIMARY_RISK_CATEGORY,
    p.NEXT_RENEWAL_DAYS,
    -- Claims metrics
    COALESCE(cl.TOTAL_CLAIMS, 0) AS TOTAL_CLAIMS,
    COALESCE(cl.OPEN_CLAIMS, 0) AS OPEN_CLAIMS,
    COALESCE(cl.DENIED_CLAIMS, 0) AS DENIED_CLAIMS,
    COALESCE(cl.TOTAL_CLAIM_AMOUNT, 0) AS TOTAL_CLAIM_AMOUNT,
    cl.AVG_SETTLEMENT_RATIO,
    cl.AVG_CLAIM_RESOLUTION_DAYS,
    cl.LAST_CLAIM_DATE,
    -- Loan metrics
    COALESCE(l.TOTAL_LOANS, 0) AS TOTAL_LOANS,
    COALESCE(l.ACTIVE_LOANS, 0) AS ACTIVE_LOANS,
    COALESCE(l.PROBLEM_LOANS, 0) AS PROBLEM_LOANS,
    COALESCE(l.TOTAL_OUTSTANDING_BALANCE, 0) AS TOTAL_OUTSTANDING_BALANCE,
    COALESCE(l.TOTAL_MONTHLY_PAYMENT, 0) AS TOTAL_MONTHLY_PAYMENT,
    COALESCE(l.MAX_DAYS_PAST_DUE, 0) AS MAX_DAYS_PAST_DUE,
    l.LOAN_TYPES,
    -- Interaction metrics
    COALESCE(i.TOTAL_INTERACTIONS, 0) AS TOTAL_INTERACTIONS,
    COALESCE(i.COMPLAINT_COUNT, 0) AS COMPLAINT_COUNT,
    COALESCE(i.ESCALATION_COUNT, 0) AS ESCALATION_COUNT,
    i.LAST_INTERACTION_DATE,
    i.PREFERRED_CHANNEL,
    COALESCE(i.DAYS_SINCE_LAST_INTERACTION, 999) AS DAYS_SINCE_LAST_INTERACTION,
    -- Call transcript metrics
    COALESCE(t.TOTAL_CALLS, 0) AS TOTAL_CALLS,
    t.LAST_CALL_DATE,
    t.AVG_CALL_DURATION,
    t.MOST_COMMON_CALL_REASON,
    -- Document metrics
    COALESCE(doc.TOTAL_DOCUMENTS, 0) AS TOTAL_DOCUMENTS,
    doc.DOCUMENT_TYPES,
    doc.LAST_DOCUMENT_DATE,
    -- Composite risk indicators
    CASE
        WHEN COALESCE(l.MAX_DAYS_PAST_DUE, 0) >= 90
          OR COALESCE(i.COMPLAINT_COUNT, 0) >= 3
          OR COALESCE(p.LAPSED_POLICIES, 0) >= 2 THEN 'High'
        WHEN COALESCE(l.MAX_DAYS_PAST_DUE, 0) >= 30
          OR COALESCE(i.COMPLAINT_COUNT, 0) >= 1
          OR COALESCE(p.LAPSED_POLICIES, 0) >= 1 THEN 'Medium'
        ELSE 'Low'
    END AS COMPOSITE_RISK_LEVEL,
    -- Customer lifetime value proxy
    COALESCE(p.TOTAL_PREMIUM, 0) * GREATEST(c.TENURE_MONTHS, 1) / 12.0 AS ESTIMATED_CLV
FROM CLEAN.DT_CUSTOMERS c
LEFT JOIN policy_agg p ON c.CUSTOMER_ID = p.CUSTOMER_ID
LEFT JOIN claims_agg cl ON c.CUSTOMER_ID = cl.CUSTOMER_ID
LEFT JOIN loan_agg l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN interaction_agg i ON c.CUSTOMER_ID = i.CUSTOMER_ID
LEFT JOIN transcript_agg t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN document_agg doc ON c.CUSTOMER_ID = doc.CUSTOMER_ID;


-- =========================================================================
-- CUSTOMER_INTERACTION_TIMELINE - Chronological event stream
-- Union of all touchpoints for timeline display
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CURATED.CUSTOMER_INTERACTION_TIMELINE
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = COMPUTE_WH
AS
-- Policy events
SELECT
    CUSTOMER_ID,
    CREATED_AT AS EVENT_DATE,
    'Policy' AS EVENT_CATEGORY,
    POLICY_TYPE || ' policy ' || LOWER(POLICY_STATUS) AS EVENT_DESCRIPTION,
    POLICY_STATUS AS EVENT_STATUS,
    PREMIUM_AMOUNT AS EVENT_AMOUNT,
    NULL AS EVENT_NOTES,
    'policy_' || POLICY_ID::VARCHAR AS EVENT_ID
FROM CLEAN.DT_POLICIES

UNION ALL

-- Claim events
SELECT
    CUSTOMER_ID,
    FILED_DATE AS EVENT_DATE,
    'Claim' AS EVENT_CATEGORY,
    CLAIM_TYPE || ' claim - ' || LOWER(CLAIM_STATUS) AS EVENT_DESCRIPTION,
    CLAIM_STATUS AS EVENT_STATUS,
    CLAIM_AMOUNT AS EVENT_AMOUNT,
    DESCRIPTION AS EVENT_NOTES,
    'claim_' || CLAIM_ID::VARCHAR AS EVENT_ID
FROM CLEAN.DT_CLAIMS

UNION ALL

-- Loan events
SELECT
    CUSTOMER_ID,
    ORIGINATION_DATE AS EVENT_DATE,
    'Loan' AS EVENT_CATEGORY,
    LOAN_TYPE || ' loan - ' || LOWER(LOAN_STATUS) AS EVENT_DESCRIPTION,
    LOAN_STATUS AS EVENT_STATUS,
    PRINCIPAL_AMOUNT AS EVENT_AMOUNT,
    NULL AS EVENT_NOTES,
    'loan_' || LOAN_ID::VARCHAR AS EVENT_ID
FROM CLEAN.DT_LOANS

UNION ALL

-- Interaction events
SELECT
    CUSTOMER_ID,
    INTERACTION_DATE AS EVENT_DATE,
    'Interaction' AS EVENT_CATEGORY,
    CHANNEL || ' - ' || INTERACTION_TYPE || ': ' || SUBJECT AS EVENT_DESCRIPTION,
    RESOLUTION_STATUS AS EVENT_STATUS,
    NULL AS EVENT_AMOUNT,
    NOTES AS EVENT_NOTES,
    'interaction_' || INTERACTION_ID::VARCHAR AS EVENT_ID
FROM CLEAN.DT_INTERACTIONS

UNION ALL

-- Call transcript events
SELECT
    CUSTOMER_ID,
    CALL_DATE AS EVENT_DATE,
    'Call' AS EVENT_CATEGORY,
    'Phone call - ' || CALL_REASON AS EVENT_DESCRIPTION,
    NULL AS EVENT_STATUS,
    NULL AS EVENT_AMOUNT,
    LEFT(TRANSCRIPT_TEXT, 500) AS EVENT_NOTES,
    'call_' || TRANSCRIPT_ID::VARCHAR AS EVENT_ID
FROM CLEAN.DT_CALL_TRANSCRIPTS

UNION ALL

-- Document events
SELECT
    TRY_CAST(CUSTOMER_ID AS NUMBER) AS CUSTOMER_ID,
    FILE_MODIFIED_AT::TIMESTAMP_NTZ AS EVENT_DATE,
    'Document' AS EVENT_CATEGORY,
    DOCUMENT_TYPE || ' - ' || COALESCE(REFERENCE_NUMBER, FILE_NAME) AS EVENT_DESCRIPTION,
    COALESCE(STATUS, 'Processed') AS EVENT_STATUS,
    TRY_CAST(REPLACE(REPLACE(AMOUNT, '$', ''), ',', '') AS FLOAT) AS EVENT_AMOUNT,
    LEFT(DESCRIPTION, 500) AS EVENT_NOTES,
    'doc_' || FILE_NAME AS EVENT_ID
FROM AI.DT_DOCUMENT_EXTRACTED
WHERE TRY_CAST(CUSTOMER_ID AS NUMBER) IS NOT NULL;
