-- =============================================================================
-- 03_clean_dynamic_tables.sql - CLEAN Layer Dynamic Tables
-- Dedup, normalize, validate, and enrich raw data
-- =============================================================================

USE DATABASE CUSTOMER_360;
USE WAREHOUSE COMPUTE_WH;

-- =========================================================================
-- DT_CUSTOMERS - Cleaned and enriched customer profiles
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_CUSTOMERS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    REGEXP_REPLACE(PHONE, '[^0-9+\\-]', '') AS PHONE,
    DOB,
    DATEDIFF('year', DOB, CURRENT_DATE()) AS AGE,
    TRIM(ADDRESS) AS ADDRESS,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    COALESCE(CUSTOMER_SEGMENT, 'Standard') AS CUSTOMER_SEGMENT,
    CREDIT_SCORE,
    ANNUAL_INCOME,
    COALESCE(EMPLOYMENT_STATUS, 'Unknown') AS EMPLOYMENT_STATUS,
    COALESCE(IS_ACTIVE, TRUE) AS IS_ACTIVE,
    CREATED_AT,
    UPDATED_AT,
    DATEDIFF('month', CREATED_AT, CURRENT_DATE()) AS TENURE_MONTHS,
    LOWER(SPLIT_PART(EMAIL, '@', 2)) AS EMAIL_DOMAIN
FROM RAW.RAW_CUSTOMERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY UPDATED_AT DESC) = 1;


-- =========================================================================
-- DT_POLICIES - Cleaned insurance policies
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_POLICIES
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    POLICY_ID,
    CUSTOMER_ID,
    UPPER(TRIM(POLICY_TYPE)) AS POLICY_TYPE,
    UPPER(TRIM(POLICY_STATUS)) AS POLICY_STATUS,
    COALESCE(PREMIUM_AMOUNT, 0) AS PREMIUM_AMOUNT,
    COALESCE(COVERAGE_AMOUNT, 0) AS COVERAGE_AMOUNT,
    COALESCE(DEDUCTIBLE_AMOUNT, 0) AS DEDUCTIBLE_AMOUNT,
    START_DATE,
    END_DATE,
    RENEWAL_DATE,
    UNDERWRITING_SCORE,
    COALESCE(RISK_CATEGORY, 'Medium') AS RISK_CATEGORY,
    CREATED_AT,
    CASE
        WHEN END_DATE < CURRENT_DATE() AND POLICY_STATUS = 'ACTIVE' THEN TRUE
        ELSE FALSE
    END AS IS_EXPIRED,
    DATEDIFF('day', CURRENT_DATE(), RENEWAL_DATE) AS DAYS_TO_RENEWAL
FROM RAW.RAW_POLICIES
QUALIFY ROW_NUMBER() OVER (PARTITION BY POLICY_ID ORDER BY CREATED_AT DESC) = 1;


-- =========================================================================
-- DT_CLAIMS - Cleaned insurance claims
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_CLAIMS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    CLAIM_ID,
    POLICY_ID,
    CUSTOMER_ID,
    INITCAP(TRIM(CLAIM_TYPE)) AS CLAIM_TYPE,
    UPPER(TRIM(CLAIM_STATUS)) AS CLAIM_STATUS,
    COALESCE(CLAIM_AMOUNT, 0) AS CLAIM_AMOUNT,
    SETTLEMENT_AMOUNT,
    FILED_DATE,
    RESOLVED_DATE,
    DESCRIPTION,
    CREATED_AT,
    CASE
        WHEN SETTLEMENT_AMOUNT IS NOT NULL AND CLAIM_AMOUNT > 0
        THEN ROUND(SETTLEMENT_AMOUNT / CLAIM_AMOUNT, 2)
        ELSE NULL
    END AS SETTLEMENT_RATIO,
    CASE
        WHEN RESOLVED_DATE IS NOT NULL
        THEN DATEDIFF('day', FILED_DATE, RESOLVED_DATE)
        ELSE DATEDIFF('day', FILED_DATE, CURRENT_DATE())
    END AS DAYS_TO_RESOLVE
FROM RAW.RAW_CLAIMS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CLAIM_ID ORDER BY CREATED_AT DESC) = 1;


-- =========================================================================
-- DT_LOANS - Cleaned lending data
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_LOANS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    LOAN_ID,
    CUSTOMER_ID,
    UPPER(TRIM(LOAN_TYPE)) AS LOAN_TYPE,
    UPPER(TRIM(LOAN_STATUS)) AS LOAN_STATUS,
    COALESCE(PRINCIPAL_AMOUNT, 0) AS PRINCIPAL_AMOUNT,
    INTEREST_RATE,
    COALESCE(MONTHLY_PAYMENT, 0) AS MONTHLY_PAYMENT,
    COALESCE(OUTSTANDING_BALANCE, 0) AS OUTSTANDING_BALANCE,
    ORIGINATION_DATE,
    MATURITY_DATE,
    COALESCE(DAYS_PAST_DUE, 0) AS DAYS_PAST_DUE,
    CREATED_AT,
    CASE
        WHEN OUTSTANDING_BALANCE > 0 AND PRINCIPAL_AMOUNT > 0
        THEN ROUND(1 - (OUTSTANDING_BALANCE / PRINCIPAL_AMOUNT), 2)
        ELSE 1.0
    END AS PAYOFF_PROGRESS,
    CASE
        WHEN DAYS_PAST_DUE >= 180 THEN 'Severe'
        WHEN DAYS_PAST_DUE >= 90 THEN 'High'
        WHEN DAYS_PAST_DUE >= 30 THEN 'Moderate'
        WHEN DAYS_PAST_DUE > 0 THEN 'Low'
        ELSE 'Current'
    END AS DELINQUENCY_CATEGORY
FROM RAW.RAW_LOANS
QUALIFY ROW_NUMBER() OVER (PARTITION BY LOAN_ID ORDER BY CREATED_AT DESC) = 1;


-- =========================================================================
-- DT_INTERACTIONS - Cleaned structured interactions
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_INTERACTIONS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    INTERACTION_ID,
    CUSTOMER_ID,
    INITCAP(TRIM(CHANNEL)) AS CHANNEL,
    INITCAP(TRIM(INTERACTION_TYPE)) AS INTERACTION_TYPE,
    TRIM(SUBJECT) AS SUBJECT,
    TRIM(NOTES) AS NOTES,
    COALESCE(UPPER(TRIM(RESOLUTION_STATUS)), 'PENDING') AS RESOLUTION_STATUS,
    AGENT_ID,
    INTERACTION_DATE,
    DURATION_SECONDS,
    CREATED_AT
FROM RAW.RAW_INTERACTIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY INTERACTION_ID ORDER BY CREATED_AT DESC) = 1;


-- =========================================================================
-- DT_CALL_TRANSCRIPTS - Cleaned call transcripts
-- =========================================================================
CREATE OR REPLACE DYNAMIC TABLE CLEAN.DT_CALL_TRANSCRIPTS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    TRANSCRIPT_ID,
    CUSTOMER_ID,
    INTERACTION_ID,
    CALL_DATE,
    DURATION_SECONDS,
    AGENT_ID,
    INITCAP(TRIM(AGENT_NAME)) AS AGENT_NAME,
    TRIM(TRANSCRIPT_TEXT) AS TRANSCRIPT_TEXT,
    INITCAP(TRIM(CALL_REASON)) AS CALL_REASON,
    LENGTH(TRANSCRIPT_TEXT) AS TRANSCRIPT_LENGTH,
    CREATED_AT
FROM RAW.RAW_CALL_TRANSCRIPTS
WHERE TRANSCRIPT_TEXT IS NOT NULL AND LENGTH(TRIM(TRANSCRIPT_TEXT)) > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRANSCRIPT_ID ORDER BY CREATED_AT DESC) = 1;
